; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[board-heltec]
board = heltec_wifi_lora_32_V3
cs = 8
rst = 12
irq = 14
io1 = 13

[board-ttgo-beam]
board = ttgo-t-beam
cs = 18
rst = 23
irq = 26
io1 = 33

; [env:heltec_wifi_lora_32_V3-AE14]
; monitor_port = COM12
; upload_port = COM12
; platform = espressif32
; board = heltec_wifi_lora_32_V3
; framework = arduino
; monitor_speed = 115200
; lib_ldf_mode = deep+
; build_type = release
; build_flags = 
; 	-D CORE_DEBUG_LEVEL=5
; 	-D CS=${board-heltec.CS}
; 	-D RST=${board-heltec.RST}
; 	-D IRQ=${board-heltec.IRQ}
; 	-D IO1=${board-heltec.IO1}
; 	; -D SHOULD_USE_LMIC=1
; 	; -D IS_GATEWAY=1
; 	-D IS_SENSOR_NODE=1
; 	-D HELTEC=1
; [env:heltec_wifi_lora_32_V3-AE1]
; monitor_port = COM12
; upload_port = COM13
; platform = espressif32
; board = heltec_wifi_lora_32_V3
; framework = arduino
; monitor_speed = 115200
; lib_ldf_mode = deep+
; build_type = release
; build_flags = 
; 	-D CORE_DEBUG_LEVEL=5
; 	-D CS=${board-heltec.CS}
; 	-D RST=${board-heltec.RST}
; 	-D IRQ=${board-heltec.IRQ}
; 	-D IO1=${board-heltec.IO1}
; 	; -D SHOULD_USE_LMIC=1
; 	; -D IS_GATEWAY=1
; 	-D IS_SENSOR_NODE=1
; 	-D HELTEC=1
; [env:heltec_wifi_lora_32_V3-AE]
; monitor_port = COM12
; upload_port = COM28
; platform = espressif32
; board = heltec_wifi_lora_32_V3
; framework = arduino
; monitor_speed = 115200
; lib_ldf_mode = deep+
; build_type = release
; build_flags = 
; 	-D CORE_DEBUG_LEVEL=5
; 	-D CS=${board-heltec.CS}
; 	-D RST=${board-heltec.RST}
; 	-D IRQ=${board-heltec.IRQ}
; 	-D IO1=${board-heltec.IO1}
; 	; -D SHOULD_USE_LMIC=1
; 	; -D IS_GATEWAY=1
; 	-D IS_SENSOR_NODE=1
; 	-D HELTEC=1


; [env:heltec_wifi_lora_32_V3_2-DE6C]
; monitor_port = COM13
; upload_port = COM13
; platform = espressif32
; board = heltec_wifi_lora_32_V3
; framework = arduino
; monitor_speed = 115200
; lib_ldf_mode = deep+
; build_type = release
; build_flags = 
; 	-D CORE_DEBUG_LEVEL=5
; 	-D CS=${board-heltec.CS}
; 	-D RST=${board-heltec.RST}
; 	-D IRQ=${board-heltec.IRQ}
; 	-D IO1=${board-heltec.IO1}
; 	-D HELTEC=1

; [env:heltec_wifi_lora_32_V3_2-DE6C_]
; monitor_port = COM19
; upload_port = COM19
; platform = espressif32
; board = heltec_wifi_lora_32_V3
; framework = arduino
; monitor_speed = 115200
; lib_ldf_mode = deep+
; build_type = release
; build_flags = 
; 	-D CORE_DEBUG_LEVEL=5
; 	-D CS=${board-heltec.CS}
; 	-D RST=${board-heltec.RST}
; 	-D IRQ=${board-heltec.IRQ}
; 	-D IO1=${board-heltec.IO1}
; 	-D HELTEC=1



[env:ttgo-t-beam-121C]
monitor_port = COM7
upload_port = COM7
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_type = release
build_flags = 
	-D CORE_DEBUG_LEVEL=5
	-D CS=${board-ttgo-beam.CS}
	-D RST=${board-ttgo-beam.RST}
	-D IRQ=${board-ttgo-beam.IRQ}
	-D IO1=${board-ttgo-beam.IO1}
	-D IS_SENSOR_NODE=1
	-D REBROADCAST_HELLO_ON_ROUTE_CHANGE=1


[env:ttgo-t-beam2-1850]
monitor_port = COM8
upload_port = COM8
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_type = release
build_flags = 
	-D CORE_DEBUG_LEVEL=5
	-D CS=${board-ttgo-beam.CS}
	-D RST=${board-ttgo-beam.RST}
	-D IRQ=${board-ttgo-beam.IRQ}
	-D IO1=${board-ttgo-beam.IO1}
	-D IS_SENSOR_NODE=1
	-D REBROADCAST_HELLO_ON_ROUTE_CHANGE=1


; [env:ttgo-t-beam2-185]
; monitor_port = COM24
; upload_port = COM24
; platform = espressif32
; board = ttgo-t-beam
; framework = arduino
; monitor_speed = 115200
; lib_ldf_mode = deep+
; build_type = release
; build_flags = 
; 	-D CORE_DEBUG_LEVEL=5
; 	-D CS=${board-ttgo-beam.CS}
; 	-D RST=${board-ttgo-beam.RST}
; 	-D IRQ=${board-ttgo-beam.IRQ}
; 	-D IO1=${board-ttgo-beam.IO1}